%%  INIT. PARAMS.
drone_params = containers.Map({'Mass', 'armLength', 'Ixx', 'Iyy', 'Izz'}, ...
    {1.25, 0.265, 0.0232, 0.0232, 0.0468});

drone_gains = containers.Map(...
    {  'P_phi',   'I_phi',   'D_phi', ...
     'P_theta', 'I_theta', 'D_theta', ...
       'P_psi',   'I_psi',   'D_psi', ...
      'P_zdot',  'I_zdot',  'D_zdot', ...
         'P_x_ddot',     'I_x_ddot',     'D_x_ddot',...
         'P_y_ddot',     'I_y_ddot',     'D_y_ddot', ...
         'P_z',     'I_z',     'D_z',}, ...
    {      0.0,       0.0001,       0.15, ...
           0.0,      0.0001,            0.3, ...
           0.1,        0.0,           1, ...
           1.0,     0.0,          0.0, ...
           1.0,      0.0,         0.3, ...
           0.000001,      0.0,         0.1, ...
           50.0,      0.0,         30});

XYZ_init = [0;0;-5];
XYZ_dot_init = [0;0;0];
RPY_init = [0;0;0];
w_init = [0;0;0];
m = drone_params('Mass');
g = 9.8;

I = [drone_params('Ixx'),             0,                     0; ...
     0,             drone_params('Iyy'),                     0; ...
     0,                               0,  drone_params('Izz')];