%%  INIT. PARAMS.
drone1_params = containers.Map({'Mass', 'armLength', 'Ixx', 'Iyy', 'Izz'}, ...
    {1.25, 0.265, 0.0232, 0.0232, 0.0468});

drone1_gains = containers.Map(...
    {  'P_phi',   'I_phi',   'D_phi', ...
     'P_theta', 'I_theta', 'D_theta', ...
       'P_psi',   'I_psi',   'D_psi', ...
      'P_zdot',  'I_zdot',  'D_zdot', ...
         'P_x',     'I_x',     'D_x',...
         'P_y',     'I_y',     'D_y', ...
         'P_z',     'I_z',     'D_z',}, ...
    {      15,       0.005,       0.9, ...
           10,      0.0,            1, ...
           10,        0.0,           1, ...
           1.0,     0.0,          0.0, ...
           10,      0.0,         0.1, ...
           10,      0.0,         0.1, ...
           10,      0.0,         0.04});

XYZ_init = [0;0;0];
XYZ_dot_init = [0;0;0];
RPY_init = [0;0;0];
w_init = [0;0;0];
m = drone1_params('Mass');
g = 9.8;

I = [drone1_params('Ixx'),             0,             0; ...
     0, drone1_params('Iyy'),             0; ...
     0,             0,  drone1_params('Izz')];