function bRi = RPY2Rot(angles)
    phi = angles(1);
    theta = angles(2);
    psi = angles(3);
    
    R_psi =   [ cos(psi)  sin(psi) 0; ...
                -sin(psi) cos(psi) 0; ...
                0         0        1];
    R_theta = [ cos(theta)  0    -sin(theta); ...
                0           1              0; ...
                sin(theta)  0     cos(theta)];
    R_phi =   [ 1          0            0; ...
                0   cos(phi)     sin(phi); ...
                0  -sin(phi)     cos(phi)];
    
    % Yaw, Pitch, Roll sequence
    bRi = R_phi * R_theta * R_psi;
end